### ISSUE TITLE
Invalid, unknown or duplicate option: -V

### ISSUE THREAD

**Issue by ivelsko** [jfy133/rma-tabuliser#1]
I ran `./rma-tabuliser -d ./eager2/metagenomic_classification/malt/ -c Taxonomy -n -r 'P' -s -t 4 -V`

and get this error repeated several times

```
Version   MEGAN Community Edition (version 6.21.7, built 23 Jun 2021)
Author(s) Daniel H. Huson
Copyright (C) 2021 Daniel H. Huson. This program comes with ABSOLUTELY NO WARRANTY.
Caught:
jloda.util.UsageException: Invalid, unknown or duplicate option: -V
, use option '-h' for help
	at jloda/jloda.swing.util.ArgsOptions.done(ArgsOptions.java:203)
	at megan/megan.tools.RMA2Info.run(RMA2Info.java:110)
	at megan/megan.tools.RMA2Info.main(RMA2Info.java:63)
```

Then it creates a `count_table.tsv` with only the headers, no entries. 

It runs fine and creates a complete `count_table.tsv` when I remove `-V`

**Comment by jfy133** [comment]
Fixed with https://github.com/jfy133/rma-tabuliser/commit/079a8135462638d57e635b4b774a03da977fdb04
