### ISSUE TITLE
Add full (standard) taxonomic lineage

### ISSUE THREAD

**Issue by ivelsko** [jfy133/rma-tabuliser#3]
Would it be possible to add an option to give the full taxonomic lineage in the output file? For example, if I select species level counts, the name includes KPCOFG as well: 

`Bacteria;Bacteroidetes;Bacteroidia;Bacteroidales;Prevotellaceae;Prevotella;Prevotella baroniae`

I see the `-mro` option is set so it already only deals with standard taxonomic levels. As far as I can tell, the only way to get this exported from MEGAN is with the csv export option `readName_to_taxonPath`, but I don't want read-level information. The `taxonPath_to_` options all include the intermediate taxonomic levels like suborder that mess up the neat 7-taxonomic level structure.

This would be useful for uploading to MetacodeR for visualization in a tree-like form

**Comment by jfy133** [comment]
Can you post an example ram2info command which outputs exactly what you're looking for?

**Comment by ivelsko** [comment]
This does it 
`rma2info -i CMC010.B0201.SG1.1_tester.rma6 -o CMC010.B0201_r2i.tsv -c2c Taxonomy -p -mro -s`

And the output looks like 
```
[D] Bacteria; [P] Bacteroidetes; [C] Bacteroidia; [O] Bacteroidales; [F] Prevotellaceae; [G] Prevotella; [S] Prevotella loescheii;      11670.0
[D] Bacteria; [P] Bacteroidetes; [C] Bacteroidia; [O] Bacteroidales; [F] Prevotellaceae; [G] Prevotella; [S] Prevotella bivia;  313.0
[D] Bacteria; [P] Bacteroidetes; [C] Bacteroidia; [O] Bacteroidales; [F] Prevotellaceae; [G] Prevotella; [S] Prevotella buccae; 1642.0
[D] Bacteria; [P] Bacteroidetes; [C] Bacteroidia; [O] Bacteroidales; [F] Prevotellaceae; [G] Prevotella; [S] Prevotella denticola;      2814.0
```

But I don't like the spaces and brackets in the ` [D] `, ` [P] ` format, and it would be helpful if those could be converted to `D_` `P_`, etc to make it easier to work with, or possibly removed

**Comment by jfy133** [comment]
Please test with the version in the associated PR.

Note: I'm not cleaning the `[D]` etc., as that's not necessarily trivial (and I don't want to diverge from `rma2info` output). That's something to request from Daniel
